resources:
- name: repo
  type: git
  source: git remote add origin https://github.com/alejandrofca/concourse.git

jobs:
- name: hello-world-job
  plan:
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      - name: the-artifact
      run:
        artifacts